server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

jwt:
  signerKey: "qRxwaQqi/h6b2vH2BwQNPts3crubfThEVAkMo2eFnDOYMYT3sLiGGXc/C6oEx8W4"