environment:
  name: DEV
server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: k8s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  rabbitmq:
    addresses: ${RABBITMQ_HOST}
jwt:
  signerKey: "qRxwaQqi/h6b2vH2BwQNPts3crubfThEVAkMo2eFnDOYMYT3sLiGGXc/C6oEx8W4"
rabbitmq:
  queue:
    json:
      name: "transaction_json"
    name: "RabbitMQ"
  exchange:
    name: "RabbitMQ_exchange"
  routing:
    key: "routing_key_demo"
    json:
      key: "transaction_key_json"
