server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: "jdbc:oracle:thin:@//localhost:1521/ORCLPDB1"
    username: SPO
    password: SPO
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
# Logging
logging:
  file:
    name: logs/demofile.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
jwt:
  signerKey: "qRxwaQqi/h6b2vH2BwQNPts3crubfThEVAkMo2eFnDOYMYT3sLiGGXc/C6oEx8W4"