server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: "jdbc:oracle:thin:@//localhost:1521/ORCLPDB1"
    username: SPO
    password: SPO
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true