replicaCount: 2

mysql:
  databaseName: identity-service

rabbitmq:
  rabbitmqHost: amqps://dqvazhep:FICFXB6FYEoekFwnxiLjF8qB7qQN8BP_@gerbil.rmq.cloudamqp.com/dqvazhep
springApp:
  image:
    repository: spring-mysql-demo
    pullPolicy: IfNotPresent
    tag: latest

mysqlVolume:
  persistentVolumeClaim:
    storageSize: 500Mi

  persistentVolume:
    storageSize: 500Mi
    pathOnHost: /var/lib/mysql

  mountPath: /var/lib/mysql
